seguridad/administrador/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name="index_admin"),
    path('listar_usuarios', views.listar_usuarios, name="listar_usuarios"),
    path('agregar_usuarios', views.agregar_usuarios, name="agregar_usuarios"),
    path('editar_usuarios/<int:id>', views.editar_usuarios, name="editar_usuarios"),
    path('eliminar_usuarios/<int:id>', views.eliminar_usuarios, name="eliminar_usuarios"),
]

seguridad/gap/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name="index_gap"),
]

seguridad/seguridad/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from usuarios.views import iniciar_sesion

urlpatterns = [
    path('', iniciar_sesion, name=""),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('usuarios/', include('usuarios.urls')),
    path('gap/', include('gap.urls')),
    path('docente/', include('docente.urls')),
    path('administrador/', include('administrador.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

seguridad/administrador/models.py
from django.db import models

# Create your models here.

seguridad/docente/models.py
from django.db import models


class Profesor(models.Model):
	RUT = models.CharField(max_length=20, blank=True, null=True)
	nombre_docente = models.CharField(max_length=100, blank=True, null=True)
	nivel_formacion_academica = models.CharField(max_length=50, blank=True, null=True)
	tipo_contrato = models.CharField(max_length=30, blank=True, null=True)
	tipo_actividad = models.CharField(max_length=30, blank=True, null=True)
	periodo = models.CharField(max_length=30, blank=True, null=True)
	sede = models.CharField(max_length=30, blank=True, null=True)
	campus = models.CharField(max_length=30, blank=True, null=True)
	facultad_programa = models.CharField(max_length=30, blank=True, null=True)
	programa = models.CharField(max_length=30, blank=True, null=True)
	nombre_curso = models.CharField(max_length=50, blank=True, null=True)
	NRC = models.CharField(max_length=30, blank=True, null=True)
	n_alumnos = models.IntegerField()
	n_alumnos_responden = models.IntegerField()
	respuestas = models.DecimalField(max_digits=5, decimal_places=3, blank=True, null=True)
	P7 = models.DecimalField(max_digits=5, decimal_places=3, blank=True, null=True, default=0)
	P1 = models.DecimalField(max_digits=5, decimal_places=3, blank=True, null=True, default=0)
	P2 = models.DecimalField(max_digits=5, decimal_places=3, blank=True, null=True, default=0)
	P3 = models.DecimalField(max_digits=5, decimal_places=3, blank=True, null=True, default=0)
	P4 = models.DecimalField(max_digits=5, decimal_places=3, blank=True, null=True, default=0)
	P5 = models.DecimalField(max_digits=5, decimal_places=3, blank=True, null=True, default=0)
	P6 = models.DecimalField(max_digits=5, decimal_places=3, blank=True, null=True, default=0)
	evaluacion_promedio = models.DecimalField(max_digits=5, decimal_places=3, blank=True, null=True, default=0)
	promedio_nota = models.DecimalField(max_digits=5, decimal_places=3, blank=True, null=True, default=0)
	email = models.EmailField(max_length=144, blank=True, null=True)

	def cambiar_porcentaje(self):
		self.P1 = round(self.P1*100,1)
		self.P2 = round(self.P2*100,1)
		self.P3 = round(self.P3*100,1)
		self.P4 = round(self.P4*100,1)
		self.P5 = round(self.P5*100,1)
		self.P6 = round(self.P6*100,1)
		self.P7 = round(self.P7*100,1)
		self.respuestas = round(self.respuestas*100,1)
		self.evaluacion_promedio = round(self.evaluacion_promedio*100,1)

		return self

	def __str__(self):
		return self.RUT

class Carrera(models.Model):
	nombre = models.CharField(max_length=100)

	def __str__(self):
		return self.nombre


class Contador(models.Model):
	RUT = models.CharField(max_length=20, unique=True)
	contador = models.PositiveIntegerField(default=0)

	def aumentar_contador(self):
		self.contador += 1
		self.save()




		

seguridad/administrador/forms.py
from django import forms
from usuario.models import Usuario

class ImportExcelForm(forms.Form):
    file  = forms.FileField(label= "Seleccione el Excel que desee subir")  

seguridad/usuarios/forms.py
from django import forms
from .models import Usuario
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class UsuarioForm(forms.ModelForm):


	
	email = forms.EmailField(widget=forms.TextInput(
			attrs = {
				'class': 'form-control',
			}
		))

	facultad = forms.Select()

	class Meta:
		model = Usuario
		fields = ('email','facultad')

class testForm(UserCreationForm):
	first_name = forms.CharField(widget=forms.TextInput(
			attrs = {
				'class': 'form-control',
			}
		))
	last_name = forms.CharField(widget=forms.TextInput(
			attrs = {
				'class': 'form-control',
			}
		))
	username = forms.CharField(widget=forms.TextInput(
			attrs = {
				'class': 'form-control',
			}
		))
	password1 = forms.CharField(widget=forms.PasswordInput(
			attrs = {
				'class': 'form-control',
			}
		))
	password2 = forms.CharField(widget=forms.PasswordInput(
			attrs = {
				'class': 'form-control',
			}
		))

	class Meta:
		model = User
		fields = ('first_name', 'last_name', 'username', 'password1', 'password2')
		help_texts = {
			'username': None,
		}

seguridad/administrador/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from usuarios.models import Usuario
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from usuarios.forms import UsuarioForm, testForm
from .resources import DocenteResource
from tablib import Dataset



# Create your views here.
def index(request):
	return render(request, 'administrador/index.html')

def listar_usuarios(request):
	#usuarios = Usuario.objects.filter(organizacion__nombre=request.user.usuario.organizacion.nombre)
	usuarios = Usuario.objects.all()
	return render(request, 'administrador/listar_usuarios.html', {'usuarios': usuarios})

def eliminar_usuarios(request, id):
	usuario = Usuario.objects.get(id=id)
	if request.method == 'POST':
		usuario.delete()
		return redirect('listar_usuarios')
	else:
		return render(request, 'administrador/borrar_usuarios.html', {'usuario': usuario})

def agregar_usuarios(request):
	contexto = {}
	if request.method == 'POST':
		form = testForm(request.POST)
		profile_form = UsuarioForm(request.POST)
		if form.is_valid() and profile_form.is_valid():
			usuario = form.save()
			perfil = profile_form.save(commit=False)
			perfil.usuario = usuario
			perfil.save()
		else:
			return render(request, 'administrador/agregar_usuarios.html', {'form': form, 'profile_form': profile_form})
		return redirect('listar_usuarios') 
		
	else:
		form = testForm()
		profile_form = UsuarioForm()

	contexto = {'form': form, 'profile_form': profile_form}

	return render(request, 'administrador/agregar_usuarios.html', contexto)

def editar_usuarios(request, id):
	usuario = Usuario.objects.get(id=id)
	user = User.objects.get(id=usuario.usuario.id)
	if request.method == 'POST':
		form =  testForm(request.POST, instance=user)
		profile_form = UsuarioForm(request.POST, instance=usuario)
		if form.is_valid() and profile_form.is_valid():
			form.save()
			profile_form.save()
			return redirect('/administrador/listar_usuarios')
		else:
			return render(request, '/administrador/listar_usuarios', {'form': form, 'profile_form': profile_form})
	else:
		form =  testForm(instance=user)
		profile_form = UsuarioForm(instance=usuario)
		context = {'form': form, 'profile_form': profile_form}
		return render(request, 'administrador/editar_usuarios.html', context)

seguridad/administrador/templates/administrador/agregar_usuarios.html
{% extends 'base/base.html'%}

{% block content %}

<div class="col-lg-12">

<div class="container">
	
<div class="col-6">
		<form method="post">
			{% csrf_token %}
			<div class="form-group">
				<label for="id_first_name">Nombre</label>
				{{form.first_name}}
			</div>
			<div class="form-group">
				<label for="id_last_name">Apellido</label>
				{{form.last_name}}
			</div>
			<div class="form-group">
				<label for="id_username">Nombre de usuario</label>
				{{form.username}}
			</div>
			<div class="form-group">
				<label for="id_password1">Contraseña</label>
				{{form.password1}}
			</div>
			<div class="form-group">
				<label for="id_password2">Confirmar contraseña</label>
				{{form.password2}}
			</div>
			<div class="form-group">
				<label for="id_email">Email</label>
				{{profile_form.email}}
			</div>
			<div class="form-group">
				<label for="id_carrera">Facultad</label>
				{{profile_form.facultad}}
			</div>

			<button type="submit" class="btn btn-danger">Agregar</button>
		</form>
	</div>
	
</body>
</div>
</div>


{% endblock %}

seguridad/administrador/templates/administrador/borrar_usuarios.html
{% extends 'base/base.html'%}
{% block content %}
	<form method="post">
		{% csrf_token %}
		<p>¿Estás seguro de eliminar a este usuario {{usuario.usuario.first_name}}?</p>
		<input type="submit" value="Eliminar">
	</form>
{% endblock %}

seguridad/administrador/templates/administrador/editar_usuarios.html
{% extends 'base/base.html' %}
{% block content %}
<form method="post">
	{% csrf_token %}
	<div class="form-group col-6">
		<label for="id_first_name">Nombre</label>
		{{form.first_name}}
	</div>
	<div class="form-group col-6">
		<label for="id_last_name">Apellido</label>
		{{form.last_name}}
	</div>
	<div class="form-group col-6">
		<label for="id_username">Nombre de usuario</label>
		{{form.username}}
	</div>
	<div class="form-group col-6">
		<label for="id_password1">Contraseña</label>
		{{form.password1}}
	</div>
	<div class="form-group col-6">
		<label for="id_password2">Confirmar contraseña</label>
		{{form.password2}}
	</div>
	<div class="form-group col-6">
		<label for="id_email">Email</label>
		{{profile_form.email}}
	</div>
	<div class="form-group col-6">
		<label for="id_facultad">Facultad</label>
		{{profile_form.facultad}}
	</div>
	<div class="form-group col-6">
		<button type="submit" class="btn btn-primary">Editar</button>
	</div>
</form>
{% endblock %}

seguridad/administrador/templates/administrador/index.html
{% extends 'base/base.html' %}

{% block content %}


{% endblock %}

seguridad/administrador/templates/administrador/listar_usuarios.html
{% extends 'base/base.html' %}
{% block content %} 
  <div class="container-fluid">
  <div class="card shadow mb-4">
            <div class="card-header py-3">
              <h6 class="m-0 font-weight-bold text-primary">USUARIOS</h6>
        
            </div>

            <div class="card-body">
              <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
        <thead>
      
        <tr>
          <td align="center"><h5><b>Usuario</h5></td>
          <td align="center"><h5><b>Nombre</h5></td>
          <td align="center"><h5><b>Apellido</h5></td>
          <td align="center"><h5><b>Email</h5></td>
          <td align="center"><h5><b>Carrera</h5></td>
          <td align="center">
          </td>
          <td align="center"> 
            <a class="btn btn-success" href="{% url 'agregar_usuarios' %}"><i class="fas fa-user"></i>  REGISTRAR</a>
          </td>
      </tr>
    </thead>

      <tbody>
        {% if usuarios %}
        {% for usuario in usuarios %}
        <tr>
          <td align="center">{{usuario}}</td>
          <td align="center">{{usuario.usuario.first_name}}</td>
          <td align="center">{{usuario.usuario.last_name}}</td>
          <td align="center">{{usuario.email}}</td>
          <td align="center">{{usuario.facultad}}</td>
          <td><a class="btn btn-primary" href="{% url 'editar_usuarios' usuario.id %}"> <i class="fas fa-edit"></i>  EDITAR</a>
          </td>
          <td align="center">
            <a class="btn btn-danger" href="{% url 'eliminar_usuarios' usuario.id %}"><i class="fas fa-user-times"></i>   ELIMINAR</a>
          </td>
        </tr>
        {% endfor %}
        
        {% else %}
        <h1>No hay registros de Usuarios.</h1>

        {% endif %}
      </tbody>
      </table>
              </div>
            </div>
          </div>
           </div>
{% endblock %}